/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 06 20:27:41 GMT 2024
 */

package org.airsonic.player.ajax;

import org.junit.Test;
import static org.junit.Assert.*;
import org.airsonic.player.ajax.ScanInfo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ScanInfo_ESTest extends ScanInfo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ScanInfo scanInfo0 = new ScanInfo(true, 0);
      boolean boolean0 = scanInfo0.isScanning();
      assertEquals(0, scanInfo0.getCount());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ScanInfo scanInfo0 = new ScanInfo(true, 0);
      int int0 = scanInfo0.getCount();
      assertEquals(0, int0);
      assertTrue(scanInfo0.isScanning());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ScanInfo scanInfo0 = new ScanInfo(true, 1263);
      int int0 = scanInfo0.getCount();
      assertTrue(scanInfo0.isScanning());
      assertEquals(1263, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ScanInfo scanInfo0 = new ScanInfo(false, (-1));
      int int0 = scanInfo0.getCount();
      assertEquals((-1), int0);
      assertFalse(scanInfo0.isScanning());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ScanInfo scanInfo0 = new ScanInfo(false, (-1));
      boolean boolean0 = scanInfo0.isScanning();
      assertEquals((-1), scanInfo0.getCount());
      assertFalse(boolean0);
  }
}
