/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 06 20:29:56 GMT 2024
 */

package org.airsonic.player.ajax;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.airsonic.player.ajax.TransferService;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TransferService_ESTest extends TransferService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TransferService transferService0 = new TransferService();
      // Undeclared exception!
      try { 
        transferService0.getUploadInfo();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/directwebremoting/WebContextFactory
         //
         verifyException("org.airsonic.player.ajax.TransferService", e);
      }
  }
}
