/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 14:08:01 GMT 2024
 */

package com.sonos.services._1;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sonos.services._1.ExtendedMetadata;
import com.sonos.services._1.MediaCollection;
import com.sonos.services._1.MediaMetadata;
import com.sonos.services._1.RelatedActions;
import com.sonos.services._1.RelatedBrowse;
import com.sonos.services._1.RelatedPlay;
import com.sonos.services._1.RelatedText;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ExtendedMetadata_ESTest extends ExtendedMetadata_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ExtendedMetadata extendedMetadata0 = new ExtendedMetadata();
      RelatedActions relatedActions0 = new RelatedActions();
      extendedMetadata0.setRelatedActions(relatedActions0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ExtendedMetadata extendedMetadata0 = new ExtendedMetadata();
      RelatedPlay relatedPlay0 = new RelatedPlay();
      extendedMetadata0.setRelatedPlay(relatedPlay0);
      assertNull(relatedPlay0.getItemType());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ExtendedMetadata extendedMetadata0 = new ExtendedMetadata();
      MediaMetadata mediaMetadata0 = new MediaMetadata();
      extendedMetadata0.setMediaMetadata(mediaMetadata0);
      assertNull(mediaMetadata0.getLanguage());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ExtendedMetadata extendedMetadata0 = new ExtendedMetadata();
      LinkedList<RelatedText> linkedList0 = new LinkedList<RelatedText>();
      RelatedText relatedText0 = new RelatedText();
      linkedList0.addFirst(relatedText0);
      extendedMetadata0.relatedText = (List<RelatedText>) linkedList0;
      List<RelatedText> list0 = extendedMetadata0.getRelatedText();
      assertTrue(list0.contains(relatedText0));
      assertNotNull(list0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ExtendedMetadata extendedMetadata0 = new ExtendedMetadata();
      RelatedPlay relatedPlay0 = new RelatedPlay();
      extendedMetadata0.relatedPlay = relatedPlay0;
      RelatedPlay relatedPlay1 = extendedMetadata0.getRelatedPlay();
      assertNull(relatedPlay1.getTitle());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ExtendedMetadata extendedMetadata0 = new ExtendedMetadata();
      LinkedList<RelatedBrowse> linkedList0 = new LinkedList<RelatedBrowse>();
      extendedMetadata0.relatedBrowse = (List<RelatedBrowse>) linkedList0;
      RelatedBrowse relatedBrowse0 = new RelatedBrowse();
      linkedList0.add(relatedBrowse0);
      List<RelatedBrowse> list0 = extendedMetadata0.getRelatedBrowse();
      assertTrue(list0.contains(relatedBrowse0));
      assertNotNull(list0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ExtendedMetadata extendedMetadata0 = new ExtendedMetadata();
      RelatedActions relatedActions0 = new RelatedActions();
      extendedMetadata0.relatedActions = relatedActions0;
      RelatedActions relatedActions1 = extendedMetadata0.getRelatedActions();
      assertSame(relatedActions1, relatedActions0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ExtendedMetadata extendedMetadata0 = new ExtendedMetadata();
      MediaMetadata mediaMetadata0 = new MediaMetadata();
      extendedMetadata0.mediaMetadata = mediaMetadata0;
      MediaMetadata mediaMetadata1 = extendedMetadata0.getMediaMetadata();
      assertNull(mediaMetadata1.getGenreId());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ExtendedMetadata extendedMetadata0 = new ExtendedMetadata();
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.TRUE;
      mediaCollection0.setUserContent(boolean0);
      extendedMetadata0.setMediaCollection(mediaCollection0);
      MediaCollection mediaCollection1 = extendedMetadata0.getMediaCollection();
      assertNull(mediaCollection1.getNarratorId());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ExtendedMetadata extendedMetadata0 = new ExtendedMetadata();
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.valueOf(true);
      mediaCollection0.setRenameable(boolean0);
      extendedMetadata0.mediaCollection = mediaCollection0;
      MediaCollection mediaCollection1 = extendedMetadata0.getMediaCollection();
      assertNull(mediaCollection1.isIsFavorite());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ExtendedMetadata extendedMetadata0 = new ExtendedMetadata();
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.FALSE;
      mediaCollection0.setReadOnly(boolean0);
      extendedMetadata0.setMediaCollection(mediaCollection0);
      MediaCollection mediaCollection1 = extendedMetadata0.getMediaCollection();
      assertNull(mediaCollection1.isCanPlay());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ExtendedMetadata extendedMetadata0 = new ExtendedMetadata();
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.valueOf(true);
      mediaCollection0.canReorderItems = boolean0;
      extendedMetadata0.setMediaCollection(mediaCollection0);
      MediaCollection mediaCollection1 = extendedMetadata0.getMediaCollection();
      assertNull(mediaCollection1.getGenre());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ExtendedMetadata extendedMetadata0 = new ExtendedMetadata();
      MediaCollection mediaCollection0 = new MediaCollection();
      extendedMetadata0.setMediaCollection(mediaCollection0);
      Boolean boolean0 = new Boolean(true);
      mediaCollection0.canDeleteItems = boolean0;
      MediaCollection mediaCollection1 = extendedMetadata0.getMediaCollection();
      assertNull(mediaCollection1.getLanguage());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ExtendedMetadata extendedMetadata0 = new ExtendedMetadata();
      List<RelatedText> list0 = extendedMetadata0.getRelatedText();
      List<RelatedText> list1 = extendedMetadata0.getRelatedText();
      assertNotNull(list1);
      assertSame(list1, list0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ExtendedMetadata extendedMetadata0 = new ExtendedMetadata();
      List<RelatedBrowse> list0 = extendedMetadata0.getRelatedBrowse();
      List<RelatedBrowse> list1 = extendedMetadata0.getRelatedBrowse();
      assertSame(list1, list0);
      assertNotNull(list1);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ExtendedMetadata extendedMetadata0 = new ExtendedMetadata();
      RelatedPlay relatedPlay0 = extendedMetadata0.getRelatedPlay();
      assertNull(relatedPlay0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ExtendedMetadata extendedMetadata0 = new ExtendedMetadata();
      RelatedActions relatedActions0 = extendedMetadata0.getRelatedActions();
      assertNull(relatedActions0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ExtendedMetadata extendedMetadata0 = new ExtendedMetadata();
      MediaCollection mediaCollection0 = extendedMetadata0.getMediaCollection();
      assertNull(mediaCollection0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ExtendedMetadata extendedMetadata0 = new ExtendedMetadata();
      MediaMetadata mediaMetadata0 = extendedMetadata0.getMediaMetadata();
      assertNull(mediaMetadata0);
  }
}
