/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 14:26:49 GMT 2024
 */

package com.sonos.services._1;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sonos.services._1.GetMediaMetadataResponse;
import com.sonos.services._1.MediaMetadata;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GetMediaMetadataResponse_ESTest extends GetMediaMetadataResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GetMediaMetadataResponse getMediaMetadataResponse0 = new GetMediaMetadataResponse();
      MediaMetadata mediaMetadata0 = new MediaMetadata();
      getMediaMetadataResponse0.setGetMediaMetadataResult(mediaMetadata0);
      MediaMetadata mediaMetadata1 = getMediaMetadataResponse0.getGetMediaMetadataResult();
      assertNull(mediaMetadata1.getMimeType());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GetMediaMetadataResponse getMediaMetadataResponse0 = new GetMediaMetadataResponse();
      MediaMetadata mediaMetadata0 = getMediaMetadataResponse0.getGetMediaMetadataResult();
      assertNull(mediaMetadata0);
  }
}
