/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 11 00:39:02 GMT 2024
 */

package org.subsonic.restapi;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.subsonic.restapi.Artist;
import org.subsonic.restapi.ArtistInfo;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ArtistInfo_ESTest extends ArtistInfo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ArtistInfo artistInfo0 = new ArtistInfo();
      LinkedList<Artist> linkedList0 = new LinkedList<Artist>();
      artistInfo0.similarArtist = (List<Artist>) linkedList0;
      Artist artist0 = new Artist();
      linkedList0.add(artist0);
      List<Artist> list0 = artistInfo0.getSimilarArtist();
      assertTrue(list0.contains(artist0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ArtistInfo artistInfo0 = new ArtistInfo();
      List<Artist> list0 = artistInfo0.getSimilarArtist();
      List<Artist> list1 = artistInfo0.getSimilarArtist();
      assertSame(list1, list0);
  }
}
