/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 11 00:35:45 GMT 2024
 */

package org.subsonic.restapi;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.subsonic.restapi.AudioTrack;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AudioTrack_ESTest extends AudioTrack_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AudioTrack audioTrack0 = new AudioTrack();
      audioTrack0.setName("org.subsonic.restapi.AudioTrack");
      String string0 = audioTrack0.getName();
      assertEquals("org.subsonic.restapi.AudioTrack", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AudioTrack audioTrack0 = new AudioTrack();
      audioTrack0.setLanguageCode("tvfxc");
      String string0 = audioTrack0.getLanguageCode();
      assertEquals("tvfxc", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AudioTrack audioTrack0 = new AudioTrack();
      audioTrack0.languageCode = "";
      String string0 = audioTrack0.getLanguageCode();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AudioTrack audioTrack0 = new AudioTrack();
      audioTrack0.setId("org.subsonic.restapi.AudioTrack");
      String string0 = audioTrack0.getId();
      assertEquals("org.subsonic.restapi.AudioTrack", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AudioTrack audioTrack0 = new AudioTrack();
      String string0 = audioTrack0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AudioTrack audioTrack0 = new AudioTrack();
      audioTrack0.setId("");
      String string0 = audioTrack0.getId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      AudioTrack audioTrack0 = new AudioTrack();
      String string0 = audioTrack0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      AudioTrack audioTrack0 = new AudioTrack();
      String string0 = audioTrack0.getLanguageCode();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      AudioTrack audioTrack0 = new AudioTrack();
      audioTrack0.setName("");
      String string0 = audioTrack0.getName();
      assertEquals("", string0);
  }
}
