/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 06 20:23:31 GMT 2024
 */

package org.airsonic.player.dao;

import org.junit.Test;
import static org.junit.Assert.*;
import org.airsonic.player.dao.PlayerDaoPlayQueueFactory;
import org.airsonic.player.domain.PlayQueue;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PlayerDaoPlayQueueFactory_ESTest extends PlayerDaoPlayQueueFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PlayerDaoPlayQueueFactory playerDaoPlayQueueFactory0 = new PlayerDaoPlayQueueFactory();
      PlayQueue playQueue0 = playerDaoPlayQueueFactory0.createPlayQueue();
      assertFalse(playQueue0.isRepeatEnabled());
  }
}
