/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 06 20:58:36 GMT 2024
 */

package org.airsonic.player.domain;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import org.airsonic.player.domain.Genre;
import org.airsonic.player.domain.Genres;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Genres_ESTest extends Genres_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Genres genres0 = new Genres();
      genres0.incrementSongCount("I>(C4iaXw");
      List<Genre> list0 = genres0.getGenres();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Genres genres0 = new Genres();
      genres0.incrementSongCount("org.airsonic.player.domain.Genre");
      genres0.incrementSongCount("org.airsonic.player.domain.Genre");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Genres genres0 = new Genres();
      List<Genre> list0 = genres0.getGenres();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Genres genres0 = new Genres();
      genres0.incrementAlbumCount("I>(C4iaXw");
  }
}
