/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 06 20:56:11 GMT 2024
 */

package org.airsonic.player.domain;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import org.airsonic.player.domain.ParamSearchResult;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ParamSearchResult_ESTest extends ParamSearchResult_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ParamSearchResult<Integer> paramSearchResult0 = new ParamSearchResult<Integer>();
      paramSearchResult0.setTotalHits(3203);
      int int0 = paramSearchResult0.getTotalHits();
      assertEquals(3203, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ParamSearchResult<String> paramSearchResult0 = new ParamSearchResult<String>();
      paramSearchResult0.setTotalHits((-1));
      int int0 = paramSearchResult0.getTotalHits();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ParamSearchResult<Object> paramSearchResult0 = new ParamSearchResult<Object>();
      paramSearchResult0.setOffset(1);
      int int0 = paramSearchResult0.getOffset();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ParamSearchResult<Object> paramSearchResult0 = new ParamSearchResult<Object>();
      paramSearchResult0.setOffset((-341));
      int int0 = paramSearchResult0.getOffset();
      assertEquals((-341), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ParamSearchResult<Object> paramSearchResult0 = new ParamSearchResult<Object>();
      List<Object> list0 = paramSearchResult0.getItems();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ParamSearchResult<Object> paramSearchResult0 = new ParamSearchResult<Object>();
      int int0 = paramSearchResult0.getTotalHits();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ParamSearchResult<Object> paramSearchResult0 = new ParamSearchResult<Object>();
      int int0 = paramSearchResult0.getOffset();
      assertEquals(0, int0);
  }
}
