/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 14:32:30 GMT 2024
 */

package com.sonos.services._1;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sonos.services._1.ItemType;
import com.sonos.services._1.MediaCollection;
import com.sonos.services._1.MediaMetadata;
import com.sonos.services._1.TagsData;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AbstractMedia_ESTest extends AbstractMedia_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MediaMetadata mediaMetadata0 = new MediaMetadata();
      mediaMetadata0.setGenreId("K&,C&\"h9gsS|N.Wjn<q");
      assertNull(mediaMetadata0.getTwitterId());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      TagsData tagsData0 = new TagsData();
      mediaCollection0.setTags(tagsData0);
      assertNull(mediaCollection0.getId());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.setSummary("favorite");
      assertNull(mediaCollection0.isIsFavorite());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = new Boolean(true);
      mediaCollection0.setOnDemand(boolean0);
      Boolean boolean1 = mediaCollection0.isOnDemand();
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.FALSE;
      mediaCollection0.setOnDemand(boolean0);
      Boolean boolean1 = mediaCollection0.isOnDemand();
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MediaMetadata mediaMetadata0 = new MediaMetadata();
      Boolean boolean0 = new Boolean(true);
      mediaMetadata0.setLiveNow(boolean0);
      Boolean boolean1 = mediaMetadata0.isLiveNow();
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.valueOf((String) null);
      mediaCollection0.liveNow = boolean0;
      Boolean boolean1 = mediaCollection0.isLiveNow();
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.TRUE;
      mediaCollection0.setIsFavorite(boolean0);
      Boolean boolean1 = mediaCollection0.isIsFavorite();
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MediaMetadata mediaMetadata0 = new MediaMetadata();
      Boolean boolean0 = new Boolean(false);
      mediaMetadata0.setIsFavorite(boolean0);
      Boolean boolean1 = mediaMetadata0.isIsFavorite();
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = new Boolean((String) null);
      mediaCollection0.setIsExplicit(boolean0);
      Boolean boolean1 = mediaCollection0.isIsExplicit();
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.setTwitterId("w59cm");
      String string0 = mediaCollection0.getTwitterId();
      assertEquals("w59cm", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MediaMetadata mediaMetadata0 = new MediaMetadata();
      mediaMetadata0.twitterId = "";
      String string0 = mediaMetadata0.getTwitterId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MediaMetadata mediaMetadata0 = new MediaMetadata();
      mediaMetadata0.setTitle("<e)9/Tz\u0001_<");
      String string0 = mediaMetadata0.getTitle();
      assertEquals("<e)9/Tz\u0001_<", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      MediaMetadata mediaMetadata0 = new MediaMetadata();
      TagsData tagsData0 = new TagsData();
      mediaMetadata0.tags = tagsData0;
      TagsData tagsData1 = mediaMetadata0.getTags();
      assertNull(tagsData1.getPremium());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.summary = "*vqjaN?";
      String string0 = mediaCollection0.getSummary();
      assertEquals("*vqjaN?", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      MediaMetadata mediaMetadata0 = new MediaMetadata();
      mediaMetadata0.summary = "";
      String string0 = mediaMetadata0.getSummary();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.language = "5g`{U9auwP#1-1>k";
      String string0 = mediaCollection0.getLanguage();
      assertEquals("5g`{U9auwP#1-1>k", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.setLanguage("");
      String string0 = mediaCollection0.getLanguage();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      MediaMetadata mediaMetadata0 = new MediaMetadata();
      ItemType itemType0 = ItemType.SEARCH;
      mediaMetadata0.itemType = itemType0;
      ItemType itemType1 = mediaMetadata0.getItemType();
      assertEquals("search", itemType1.value());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.setId("$u,+bVu;O.ekT8)");
      String string0 = mediaCollection0.getId();
      assertEquals("$u,+bVu;O.ekT8)", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.genreId = "1\"G~ *?v- ]";
      String string0 = mediaCollection0.getGenreId();
      assertEquals("1\"G~ *?v- ]", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.genreId = "";
      String string0 = mediaCollection0.getGenreId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.genre = "9+>!`+4";
      String string0 = mediaCollection0.getGenre();
      assertEquals("9+>!`+4", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.setGenre("");
      String string0 = mediaCollection0.getGenre();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.setDisplayType("com.sonos.services._1.BehaviorsData");
      String string0 = mediaCollection0.getDisplayType();
      assertEquals("com.sonos.services._1.BehaviorsData", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.displayType = "";
      String string0 = mediaCollection0.getDisplayType();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.country = "J\"bP3oM`r";
      String string0 = mediaCollection0.getCountry();
      assertEquals("J\"bP3oM`r", string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      MediaMetadata mediaMetadata0 = new MediaMetadata();
      mediaMetadata0.setCountry("");
      String string0 = mediaMetadata0.getCountry();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      String string0 = mediaCollection0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      String string0 = mediaCollection0.getLanguage();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      String string0 = mediaCollection0.getTwitterId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      String string0 = mediaCollection0.getDisplayType();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      MediaMetadata mediaMetadata0 = new MediaMetadata();
      mediaMetadata0.getItemType();
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      String string0 = mediaCollection0.getGenre();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = mediaCollection0.isIsFavorite();
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = mediaCollection0.isOnDemand();
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      ItemType itemType0 = ItemType.AUDIOBOOK;
      mediaCollection0.setItemType(itemType0);
      assertNull(mediaCollection0.getAuthor());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.setTitle("");
      String string0 = mediaCollection0.getTitle();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = mediaCollection0.isLiveNow();
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      String string0 = mediaCollection0.getCountry();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      MediaMetadata mediaMetadata0 = new MediaMetadata();
      String string0 = mediaMetadata0.getTitle();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.TRUE;
      mediaCollection0.setIsExplicit(boolean0);
      Boolean boolean1 = mediaCollection0.isIsExplicit();
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = mediaCollection0.isIsExplicit();
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      String string0 = mediaCollection0.getSummary();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      String string0 = mediaCollection0.getGenreId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      TagsData tagsData0 = mediaCollection0.getTags();
      assertNull(tagsData0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.setId("");
      String string0 = mediaCollection0.getId();
      assertEquals("", string0);
  }
}
