/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 13:29:43 GMT 2024
 */

package com.sonos.services._1;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sonos.services._1.AlbumArtUrl;
import com.sonos.services._1.MediaCollection;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MediaCollection_ESTest extends MediaCollection_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.TRUE;
      mediaCollection0.setReadOnly(boolean0);
      assertNull(mediaCollection0.getAuthor());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      AlbumArtUrl albumArtUrl0 = new AlbumArtUrl();
      mediaCollection0.setAlbumArtURI(albumArtUrl0);
      assertNull(mediaCollection0.isCanPlay());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.FALSE;
      mediaCollection0.setContainsFavorite(boolean0);
      assertNull(mediaCollection0.getAuthor());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.TRUE;
      mediaCollection0.setCanEnumerate(boolean0);
      assertTrue(mediaCollection0.isCanEnumerate());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = new Boolean(true);
      mediaCollection0.setRenameable(boolean0);
      boolean boolean1 = mediaCollection0.isRenameable();
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = new Boolean(true);
      mediaCollection0.setHomogeneous(boolean0);
      Boolean boolean1 = mediaCollection0.isHomogeneous();
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.FALSE;
      mediaCollection0.setHomogeneous(boolean0);
      Boolean boolean1 = mediaCollection0.isHomogeneous();
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.valueOf(true);
      mediaCollection0.containsFavorite = boolean0;
      Boolean boolean1 = mediaCollection0.isContainsFavorite();
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.valueOf("show");
      mediaCollection0.containsFavorite = boolean0;
      Boolean boolean1 = mediaCollection0.isContainsFavorite();
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.TRUE;
      mediaCollection0.setCanSkip(boolean0);
      Boolean boolean1 = mediaCollection0.isCanSkip();
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = new Boolean("eXBpb");
      mediaCollection0.setCanSkip(boolean0);
      Boolean boolean1 = mediaCollection0.isCanSkip();
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.TRUE;
      mediaCollection0.canScroll = boolean0;
      Boolean boolean1 = mediaCollection0.isCanScroll();
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.valueOf("{ag~");
      mediaCollection0.setCanScroll(boolean0);
      Boolean boolean1 = mediaCollection0.isCanScroll();
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.TRUE;
      mediaCollection0.canResume = boolean0;
      Boolean boolean1 = mediaCollection0.isCanResume();
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.valueOf(false);
      mediaCollection0.setCanResume(boolean0);
      Boolean boolean1 = mediaCollection0.isCanResume();
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.TRUE;
      mediaCollection0.setCanPlay(boolean0);
      Boolean boolean1 = mediaCollection0.isCanPlay();
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.valueOf("^>F|8ROlx");
      mediaCollection0.setCanPlay(boolean0);
      Boolean boolean1 = mediaCollection0.isCanPlay();
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.valueOf(true);
      mediaCollection0.canEnumerate = boolean0;
      Boolean boolean1 = mediaCollection0.isCanEnumerate();
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = new Boolean("=sz{'>w5'V");
      mediaCollection0.canEnumerate = boolean0;
      Boolean boolean1 = mediaCollection0.isCanEnumerate();
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.TRUE;
      mediaCollection0.canCache = boolean0;
      Boolean boolean1 = mediaCollection0.isCanCache();
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.FALSE;
      mediaCollection0.setCanCache(boolean0);
      Boolean boolean1 = mediaCollection0.isCanCache();
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.TRUE;
      mediaCollection0.setCanAddToFavorites(boolean0);
      Boolean boolean1 = mediaCollection0.isCanAddToFavorites();
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.valueOf("^>F|8ROlx");
      mediaCollection0.setCanAddToFavorites(boolean0);
      Boolean boolean1 = mediaCollection0.isCanAddToFavorites();
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.TRUE;
      mediaCollection0.setCanAddToFavorite(boolean0);
      Boolean boolean1 = mediaCollection0.isCanAddToFavorite();
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.valueOf((String) null);
      mediaCollection0.canAddToFavorite = boolean0;
      Boolean boolean1 = mediaCollection0.isCanAddToFavorite();
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = new Boolean(true);
      mediaCollection0.authRequired = boolean0;
      Boolean boolean1 = mediaCollection0.isAuthRequired();
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.FALSE;
      mediaCollection0.setAuthRequired(boolean0);
      Boolean boolean1 = mediaCollection0.isAuthRequired();
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.setNarratorId("com.sonos.services._1.MediaCollection");
      String string0 = mediaCollection0.getNarratorId();
      assertEquals("com.sonos.services._1.MediaCollection", string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.setNarratorId("");
      String string0 = mediaCollection0.getNarratorId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.narrator = "K>qu}+yB_V7";
      String string0 = mediaCollection0.getNarrator();
      assertEquals("K>qu}+yB_V7", string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.narrator = "";
      String string0 = mediaCollection0.getNarrator();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.setAuthorId("TA\u0000hzcn,N^5V)/7");
      String string0 = mediaCollection0.getAuthorId();
      assertEquals("TA\u0000hzcn,N^5V)/7", string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.setAuthor("eXBpb");
      String string0 = mediaCollection0.getAuthor();
      assertEquals("eXBpb", string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.setAuthor("");
      String string0 = mediaCollection0.getAuthor();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.artistId = "^dO;K#>p3";
      String string0 = mediaCollection0.getArtistId();
      assertEquals("^dO;K#>p3", string0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.artistId = "";
      String string0 = mediaCollection0.getArtistId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.setArtist("com.sonos.services._1.MediaCollection");
      String string0 = mediaCollection0.getArtist();
      assertEquals("com.sonos.services._1.MediaCollection", string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.artist = "";
      String string0 = mediaCollection0.getArtist();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      AlbumArtUrl albumArtUrl0 = new AlbumArtUrl();
      mediaCollection0.albumArtURI = albumArtUrl0;
      AlbumArtUrl albumArtUrl1 = mediaCollection0.getAlbumArtURI();
      assertSame(albumArtUrl1, albumArtUrl0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      boolean boolean0 = mediaCollection0.isUserContent();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.TRUE;
      mediaCollection0.setUserContent(boolean0);
      boolean boolean1 = mediaCollection0.isUserContent();
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      boolean boolean0 = mediaCollection0.isRenameable();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      boolean boolean0 = mediaCollection0.isCanDeleteItems();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.TRUE;
      mediaCollection0.setCanDeleteItems(boolean0);
      boolean boolean1 = mediaCollection0.isCanDeleteItems();
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      boolean boolean0 = mediaCollection0.isCanReorderItems();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.TRUE;
      mediaCollection0.setCanReorderItems(boolean0);
      boolean boolean1 = mediaCollection0.isCanReorderItems();
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      boolean boolean0 = mediaCollection0.isReadOnly();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = Boolean.valueOf((String) null);
      mediaCollection0.readOnly = boolean0;
      boolean boolean1 = mediaCollection0.isReadOnly();
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      String string0 = mediaCollection0.getArtistId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      String string0 = mediaCollection0.getArtist();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      AlbumArtUrl albumArtUrl0 = mediaCollection0.getAlbumArtURI();
      assertNull(albumArtUrl0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      String string0 = mediaCollection0.getNarratorId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.setArtistId("s+ok{mWR  ?(I");
      assertNull(mediaCollection0.getId());
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = mediaCollection0.isHomogeneous();
      mediaCollection0.setCanReorderItems(boolean0);
      assertNull(mediaCollection0.isCanResume());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = mediaCollection0.isCanPlay();
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = mediaCollection0.isCanSkip();
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = mediaCollection0.isCanCache();
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = mediaCollection0.isCanAddToFavorites();
      mediaCollection0.setRenameable(boolean0);
      assertNull(mediaCollection0.isContainsFavorite());
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = mediaCollection0.isContainsFavorite();
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      String string0 = mediaCollection0.getAuthorId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.setAuthorId("");
      String string0 = mediaCollection0.getAuthorId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      mediaCollection0.setNarrator("artistTrackList");
      assertNull(mediaCollection0.getAuthor());
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = mediaCollection0.isCanScroll();
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = mediaCollection0.isCanResume();
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      String string0 = mediaCollection0.getAuthor();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = mediaCollection0.isAuthRequired();
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = mediaCollection0.isCanAddToFavorite();
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      Boolean boolean0 = mediaCollection0.isCanEnumerate();
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      MediaCollection mediaCollection0 = new MediaCollection();
      String string0 = mediaCollection0.getNarrator();
      assertNull(string0);
  }
}
