/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 14:33:26 GMT 2024
 */

package com.sonos.services._1;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sonos.services._1.ItemRating;
import com.sonos.services._1.RateItemResponse;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RateItemResponse_ESTest extends RateItemResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RateItemResponse rateItemResponse0 = new RateItemResponse();
      ItemRating itemRating0 = new ItemRating();
      rateItemResponse0.rateItemResult = itemRating0;
      ItemRating itemRating1 = rateItemResponse0.getRateItemResult();
      assertNull(itemRating1.getMessageStringId());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RateItemResponse rateItemResponse0 = new RateItemResponse();
      ItemRating itemRating0 = rateItemResponse0.getRateItemResult();
      assertNull(itemRating0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RateItemResponse rateItemResponse0 = new RateItemResponse();
      ItemRating itemRating0 = new ItemRating();
      rateItemResponse0.setRateItemResult(itemRating0);
      assertNull(itemRating0.isShouldSkip());
  }
}
