/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 14:29:00 GMT 2024
 */

package com.sonos.services._1;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sonos.services._1.ReportPlayStatusResponse;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ReportPlayStatusResponse_ESTest extends ReportPlayStatusResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ReportPlayStatusResponse reportPlayStatusResponse0 = new ReportPlayStatusResponse();
  }
}
