/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 12 01:02:02 GMT 2024
 */

package com.sonos.services._1;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sonos.services._1.Context;
import java.util.LinkedList;
import java.util.List;
import javax.imageio.metadata.IIOMetadataNode;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.w3c.dom.Element;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Context_ESTest extends Context_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Context context0 = new Context();
      context0.timeZone = "5/J!)`,j1\"O{Z6RiuK";
      String string0 = context0.getTimeZone();
      assertEquals("5/J!)`,j1\"O{Z6RiuK", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Context context0 = new Context();
      context0.setTimeZone("");
      String string0 = context0.getTimeZone();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Context context0 = new Context();
      LinkedList<Element> linkedList0 = new LinkedList<Element>();
      context0.any = (List<Element>) linkedList0;
      IIOMetadataNode iIOMetadataNode0 = new IIOMetadataNode();
      linkedList0.add((Element) iIOMetadataNode0);
      List<Element> list0 = context0.getAny();
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Context context0 = new Context();
      context0.getAny();
      List<Element> list0 = context0.getAny();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Context context0 = new Context();
      String string0 = context0.getTimeZone();
      assertNull(string0);
  }
}
