/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 12 01:13:16 GMT 2024
 */

package com.sonos.services._1;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sonos.services._1.CreateContainer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CreateContainer_ESTest extends CreateContainer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CreateContainer createContainer0 = new CreateContainer();
      createContainer0.setTitle("");
      String string0 = createContainer0.getTitle();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CreateContainer createContainer0 = new CreateContainer();
      createContainer0.setSeedId("yOVi0MeoRT");
      String string0 = createContainer0.getSeedId();
      assertEquals("yOVi0MeoRT", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CreateContainer createContainer0 = new CreateContainer();
      createContainer0.setSeedId("");
      String string0 = createContainer0.getSeedId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CreateContainer createContainer0 = new CreateContainer();
      createContainer0.setParentId("");
      String string0 = createContainer0.getParentId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CreateContainer createContainer0 = new CreateContainer();
      createContainer0.setContainerType("");
      String string0 = createContainer0.getContainerType();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CreateContainer createContainer0 = new CreateContainer();
      String string0 = createContainer0.getParentId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CreateContainer createContainer0 = new CreateContainer();
      createContainer0.setTitle("2\"@(1n");
      String string0 = createContainer0.getTitle();
      assertEquals("2\"@(1n", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CreateContainer createContainer0 = new CreateContainer();
      String string0 = createContainer0.getSeedId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CreateContainer createContainer0 = new CreateContainer();
      createContainer0.setContainerType("rUd{Mwi\"M]S^0Ec");
      String string0 = createContainer0.getContainerType();
      assertEquals("rUd{Mwi\"M]S^0Ec", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CreateContainer createContainer0 = new CreateContainer();
      String string0 = createContainer0.getContainerType();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CreateContainer createContainer0 = new CreateContainer();
      createContainer0.setParentId("2\"@(1n");
      String string0 = createContainer0.getParentId();
      assertEquals("2\"@(1n", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CreateContainer createContainer0 = new CreateContainer();
      String string0 = createContainer0.getTitle();
      assertNull(string0);
  }
}
