/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 12 01:41:58 GMT 2024
 */

package com.sonos.services._1;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sonos.services._1.ContentKey;
import com.sonos.services._1.GetContentKeyResponse;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GetContentKeyResponse_ESTest extends GetContentKeyResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GetContentKeyResponse getContentKeyResponse0 = new GetContentKeyResponse();
      ContentKey contentKey0 = new ContentKey();
      getContentKeyResponse0.setContentKey(contentKey0);
      ContentKey contentKey1 = getContentKeyResponse0.getContentKey();
      assertSame(contentKey1, contentKey0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GetContentKeyResponse getContentKeyResponse0 = new GetContentKeyResponse();
      ContentKey contentKey0 = getContentKeyResponse0.getContentKey();
      assertNull(contentKey0);
  }
}
