/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 12 01:40:54 GMT 2024
 */

package com.sonos.services._1;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sonos.services._1.GetScrollIndices;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GetScrollIndices_ESTest extends GetScrollIndices_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GetScrollIndices getScrollIndices0 = new GetScrollIndices();
      getScrollIndices0.id = "";
      getScrollIndices0.id = "Vk}fI";
      String string0 = getScrollIndices0.getId();
      assertEquals("Vk}fI", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GetScrollIndices getScrollIndices0 = new GetScrollIndices();
      getScrollIndices0.id = "";
      String string0 = getScrollIndices0.getId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GetScrollIndices getScrollIndices0 = new GetScrollIndices();
      getScrollIndices0.setId("");
      assertEquals("", getScrollIndices0.getId());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      GetScrollIndices getScrollIndices0 = new GetScrollIndices();
      String string0 = getScrollIndices0.getId();
      assertNull(string0);
  }
}
