/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 12 01:47:22 GMT 2024
 */

package com.sonos.services._1;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sonos.services._1.OpenUrlAction;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class OpenUrlAction_ESTest extends OpenUrlAction_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      OpenUrlAction openUrlAction0 = new OpenUrlAction();
      openUrlAction0.url = "";
      String string0 = openUrlAction0.getUrl();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      OpenUrlAction openUrlAction0 = new OpenUrlAction();
      String string0 = openUrlAction0.getUrl();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      OpenUrlAction openUrlAction0 = new OpenUrlAction();
      openUrlAction0.setUrl("Q 7I+");
      String string0 = openUrlAction0.getUrl();
      assertEquals("Q 7I+", string0);
  }
}
