/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 12 01:19:09 GMT 2024
 */

package com.sonos.services._1;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sonos.services._1.RelatedBrowse;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RelatedBrowse_ESTest extends RelatedBrowse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RelatedBrowse relatedBrowse0 = new RelatedBrowse();
      relatedBrowse0.type = "SxQl)Waf1.$,";
      relatedBrowse0.type = "";
      String string0 = relatedBrowse0.getType();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RelatedBrowse relatedBrowse0 = new RelatedBrowse();
      relatedBrowse0.setId("");
      String string0 = relatedBrowse0.getId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RelatedBrowse relatedBrowse0 = new RelatedBrowse();
      String string0 = relatedBrowse0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RelatedBrowse relatedBrowse0 = new RelatedBrowse();
      String string0 = relatedBrowse0.getType();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RelatedBrowse relatedBrowse0 = new RelatedBrowse();
      relatedBrowse0.setId("SxQl)Waf1.$,");
      String string0 = relatedBrowse0.getId();
      assertEquals("SxQl)Waf1.$,", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      RelatedBrowse relatedBrowse0 = new RelatedBrowse();
      relatedBrowse0.setType("\"6ae");
      String string0 = relatedBrowse0.getType();
      assertEquals("\"6ae", string0);
  }
}
