/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 12 01:23:47 GMT 2024
 */

package com.sonos.services._1;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sonos.services._1.RenameContainer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RenameContainer_ESTest extends RenameContainer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RenameContainer renameContainer0 = new RenameContainer();
      renameContainer0.setTitle("$[wmJKm[i-.");
      String string0 = renameContainer0.getTitle();
      assertEquals("$[wmJKm[i-.", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RenameContainer renameContainer0 = new RenameContainer();
      renameContainer0.title = "";
      String string0 = renameContainer0.getTitle();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RenameContainer renameContainer0 = new RenameContainer();
      renameContainer0.setId("n]uCC*Qb#");
      String string0 = renameContainer0.getId();
      assertEquals("n]uCC*Qb#", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RenameContainer renameContainer0 = new RenameContainer();
      renameContainer0.id = "";
      String string0 = renameContainer0.getId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RenameContainer renameContainer0 = new RenameContainer();
      String string0 = renameContainer0.getTitle();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      RenameContainer renameContainer0 = new RenameContainer();
      String string0 = renameContainer0.getId();
      assertNull(string0);
  }
}
