/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 12 01:17:24 GMT 2024
 */

package com.sonos.services._1;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sonos.services._1.ReportPlaySecondsResult;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ReportPlaySecondsResult_ESTest extends ReportPlaySecondsResult_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ReportPlaySecondsResult reportPlaySecondsResult0 = new ReportPlaySecondsResult();
      reportPlaySecondsResult0.interval = 1;
      int int0 = reportPlaySecondsResult0.getInterval();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ReportPlaySecondsResult reportPlaySecondsResult0 = new ReportPlaySecondsResult();
      reportPlaySecondsResult0.setInterval((-857));
      int int0 = reportPlaySecondsResult0.getInterval();
      assertEquals((-857), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ReportPlaySecondsResult reportPlaySecondsResult0 = new ReportPlaySecondsResult();
      int int0 = reportPlaySecondsResult0.getInterval();
      assertEquals(0, int0);
  }
}
