/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 12 01:21:16 GMT 2024
 */

package com.sonos.services._1;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sonos.services._1.ReportPlayStatus;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ReportPlayStatus_ESTest extends ReportPlayStatus_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ReportPlayStatus reportPlayStatus0 = new ReportPlayStatus();
      reportPlayStatus0.setStatus("");
      String string0 = reportPlayStatus0.getStatus();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ReportPlayStatus reportPlayStatus0 = new ReportPlayStatus();
      Integer integer0 = new Integer(0);
      reportPlayStatus0.offsetMillis = integer0;
      Integer integer1 = reportPlayStatus0.getOffsetMillis();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ReportPlayStatus reportPlayStatus0 = new ReportPlayStatus();
      Integer integer0 = new Integer((-1976));
      reportPlayStatus0.setOffsetMillis(integer0);
      Integer integer1 = reportPlayStatus0.getOffsetMillis();
      assertEquals((-1976), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ReportPlayStatus reportPlayStatus0 = new ReportPlayStatus();
      Integer integer0 = new Integer(443);
      reportPlayStatus0.offsetMillis = integer0;
      Integer integer1 = reportPlayStatus0.getOffsetMillis();
      assertEquals(443, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ReportPlayStatus reportPlayStatus0 = new ReportPlayStatus();
      reportPlayStatus0.setId("80AwW0ek`jl{EH");
      String string0 = reportPlayStatus0.getId();
      assertEquals("80AwW0ek`jl{EH", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ReportPlayStatus reportPlayStatus0 = new ReportPlayStatus();
      reportPlayStatus0.setId("");
      String string0 = reportPlayStatus0.getId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ReportPlayStatus reportPlayStatus0 = new ReportPlayStatus();
      reportPlayStatus0.setContextId("");
      String string0 = reportPlayStatus0.getContextId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ReportPlayStatus reportPlayStatus0 = new ReportPlayStatus();
      String string0 = reportPlayStatus0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ReportPlayStatus reportPlayStatus0 = new ReportPlayStatus();
      String string0 = reportPlayStatus0.getStatus();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ReportPlayStatus reportPlayStatus0 = new ReportPlayStatus();
      reportPlayStatus0.setStatus("uUJ6[oK");
      String string0 = reportPlayStatus0.getStatus();
      assertEquals("uUJ6[oK", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ReportPlayStatus reportPlayStatus0 = new ReportPlayStatus();
      reportPlayStatus0.setContextId("I6=wyeuG)0VIPw~U");
      String string0 = reportPlayStatus0.getContextId();
      assertEquals("I6=wyeuG)0VIPw~U", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ReportPlayStatus reportPlayStatus0 = new ReportPlayStatus();
      String string0 = reportPlayStatus0.getContextId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ReportPlayStatus reportPlayStatus0 = new ReportPlayStatus();
      Integer integer0 = reportPlayStatus0.getOffsetMillis();
      assertNull(integer0);
  }
}
