/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 15:54:23 GMT 2024
 */

package org.subsonic.restapi;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.subsonic.restapi.Captions;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Captions_ESTest extends Captions_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Captions captions0 = new Captions();
      captions0.setName("'i,o.uS>");
      String string0 = captions0.getName();
      assertEquals("'i,o.uS>", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Captions captions0 = new Captions();
      captions0.name = "";
      String string0 = captions0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Captions captions0 = new Captions();
      captions0.setId("`M+LZ.1t,4fhE");
      String string0 = captions0.getId();
      assertEquals("`M+LZ.1t,4fhE", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Captions captions0 = new Captions();
      String string0 = captions0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Captions captions0 = new Captions();
      captions0.setId("");
      String string0 = captions0.getId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Captions captions0 = new Captions();
      String string0 = captions0.getId();
      assertNull(string0);
  }
}
