/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 14:36:11 GMT 2024
 */

package com.sonos.services._1;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sonos.services._1.GetAppLink;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GetAppLink_ESTest extends GetAppLink_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      GetAppLink getAppLink0 = new GetAppLink();
      getAppLink0.setCallbackPath("");
      assertNull(getAppLink0.getOsVersion());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      GetAppLink getAppLink0 = new GetAppLink();
      getAppLink0.setSonosAppName("]kHEfL@hT)1pKKp^x|");
      String string0 = getAppLink0.getSonosAppName();
      assertEquals("]kHEfL@hT)1pKKp^x|", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      GetAppLink getAppLink0 = new GetAppLink();
      getAppLink0.sonosAppName = "";
      String string0 = getAppLink0.getSonosAppName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      GetAppLink getAppLink0 = new GetAppLink();
      getAppLink0.setOsVersion("!}SVL%W&N%T3AzD");
      String string0 = getAppLink0.getOsVersion();
      assertEquals("!}SVL%W&N%T3AzD", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      GetAppLink getAppLink0 = new GetAppLink();
      getAppLink0.householdId = "}";
      String string0 = getAppLink0.getHouseholdId();
      assertEquals("}", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      GetAppLink getAppLink0 = new GetAppLink();
      getAppLink0.setHouseholdId("");
      String string0 = getAppLink0.getHouseholdId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      GetAppLink getAppLink0 = new GetAppLink();
      getAppLink0.setHardware("f7I=Y");
      String string0 = getAppLink0.getHardware();
      assertEquals("f7I=Y", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      GetAppLink getAppLink0 = new GetAppLink();
      getAppLink0.callbackPath = "93Hku:<O~/[Nv\"3SA~";
      String string0 = getAppLink0.getCallbackPath();
      assertEquals("93Hku:<O~/[Nv\"3SA~", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      GetAppLink getAppLink0 = new GetAppLink();
      getAppLink0.callbackPath = "";
      String string0 = getAppLink0.getCallbackPath();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      GetAppLink getAppLink0 = new GetAppLink();
      String string0 = getAppLink0.getHardware();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      GetAppLink getAppLink0 = new GetAppLink();
      String string0 = getAppLink0.getHouseholdId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      GetAppLink getAppLink0 = new GetAppLink();
      getAppLink0.setOsVersion("");
      String string0 = getAppLink0.getOsVersion();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      GetAppLink getAppLink0 = new GetAppLink();
      String string0 = getAppLink0.getOsVersion();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      GetAppLink getAppLink0 = new GetAppLink();
      String string0 = getAppLink0.getCallbackPath();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      GetAppLink getAppLink0 = new GetAppLink();
      String string0 = getAppLink0.getSonosAppName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      GetAppLink getAppLink0 = new GetAppLink();
      getAppLink0.setHardware("");
      String string0 = getAppLink0.getHardware();
      assertEquals("", string0);
  }
}
