/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 14:36:14 GMT 2024
 */

package com.sonos.services._1;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sonos.services._1.GetDeviceLinkCode;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GetDeviceLinkCode_ESTest extends GetDeviceLinkCode_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GetDeviceLinkCode getDeviceLinkCode0 = new GetDeviceLinkCode();
      getDeviceLinkCode0.setHouseholdId("i+KY-vG");
      String string0 = getDeviceLinkCode0.getHouseholdId();
      assertEquals("i+KY-vG", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GetDeviceLinkCode getDeviceLinkCode0 = new GetDeviceLinkCode();
      getDeviceLinkCode0.setHouseholdId("");
      String string0 = getDeviceLinkCode0.getHouseholdId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GetDeviceLinkCode getDeviceLinkCode0 = new GetDeviceLinkCode();
      String string0 = getDeviceLinkCode0.getHouseholdId();
      assertNull(string0);
  }
}
