/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 15:39:34 GMT 2024
 */

package org.subsonic.restapi;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.subsonic.restapi.AlbumList;
import org.subsonic.restapi.Child;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AlbumList_ESTest extends AlbumList_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AlbumList albumList0 = new AlbumList();
      LinkedList<Child> linkedList0 = new LinkedList<Child>();
      albumList0.album = (List<Child>) linkedList0;
      Child child0 = new Child();
      linkedList0.offer(child0);
      List<Child> list0 = albumList0.getAlbum();
      assertTrue(list0.contains(child0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AlbumList albumList0 = new AlbumList();
      List<Child> list0 = albumList0.getAlbum();
      List<Child> list1 = albumList0.getAlbum();
      assertSame(list1, list0);
  }
}
