/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 15:13:05 GMT 2024
 */

package org.subsonic.restapi;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.subsonic.restapi.InternetRadioStation;
import org.subsonic.restapi.InternetRadioStations;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class InternetRadioStations_ESTest extends InternetRadioStations_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      InternetRadioStations internetRadioStations0 = new InternetRadioStations();
      LinkedList<InternetRadioStation> linkedList0 = new LinkedList<InternetRadioStation>();
      internetRadioStations0.internetRadioStation = (List<InternetRadioStation>) linkedList0;
      InternetRadioStation internetRadioStation0 = new InternetRadioStation();
      linkedList0.add(internetRadioStation0);
      List<InternetRadioStation> list0 = internetRadioStations0.getInternetRadioStation();
      assertTrue(list0.contains(internetRadioStation0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      InternetRadioStations internetRadioStations0 = new InternetRadioStations();
      internetRadioStations0.getInternetRadioStation();
      List<InternetRadioStation> list0 = internetRadioStations0.getInternetRadioStation();
      assertEquals(0, list0.size());
  }
}
