/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 15:17:53 GMT 2024
 */

package org.subsonic.restapi;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.subsonic.restapi.Child;
import org.subsonic.restapi.Videos;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Videos_ESTest extends Videos_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Videos videos0 = new Videos();
      LinkedList<Child> linkedList0 = new LinkedList<Child>();
      videos0.video = (List<Child>) linkedList0;
      Child child0 = new Child();
      linkedList0.add(child0);
      List<Child> list0 = videos0.getVideo();
      assertTrue(list0.contains(child0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Videos videos0 = new Videos();
      List<Child> list0 = videos0.getVideo();
      List<Child> list1 = videos0.getVideo();
      assertSame(list1, list0);
  }
}
