/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 06 20:43:34 GMT 2024
 */

package org.airsonic.player.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.airsonic.player.domain.Player;
import org.airsonic.player.domain.PlayerTechnology;
import org.airsonic.player.service.JukeboxJavaService;
import org.airsonic.player.service.JukeboxLegacySubsonicService;
import org.airsonic.player.service.JukeboxService;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JukeboxService_ESTest extends JukeboxService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      PlayerTechnology playerTechnology0 = PlayerTechnology.JUKEBOX;
      player0.setTechnology(playerTechnology0);
      // Undeclared exception!
      try { 
        jukeboxService0.skip(player0, 96, 92);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/airsonic/player/service/SecurityService
         //
         verifyException("org.airsonic.player.service.JukeboxLegacySubsonicService", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      PlayerTechnology playerTechnology0 = PlayerTechnology.JUKEBOX;
      player0.setTechnology(playerTechnology0);
      jukeboxService0.setGain(player0, (-4072));
      jukeboxService0.getGain(player0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      JukeboxService jukeboxService0 = new JukeboxService((JukeboxLegacySubsonicService) null, (JukeboxJavaService) null);
      Player player0 = new Player();
      PlayerTechnology playerTechnology0 = PlayerTechnology.JUKEBOX;
      player0.setTechnology(playerTechnology0);
      // Undeclared exception!
      try { 
        jukeboxService0.canControl(player0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.airsonic.player.service.JukeboxService", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      PlayerTechnology playerTechnology0 = PlayerTechnology.JAVA_JUKEBOX;
      player0.setTechnology(playerTechnology0);
      jukeboxService0.canControl(player0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      jukeboxService0.canControl(player0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      PlayerTechnology playerTechnology0 = PlayerTechnology.JUKEBOX;
      player0.setTechnology(playerTechnology0);
      jukeboxService0.canControl(player0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      PlayerTechnology playerTechnology0 = PlayerTechnology.JAVA_JUKEBOX;
      player0.setTechnology(playerTechnology0);
      // Undeclared exception!
      try { 
        jukeboxService0.skip(player0, 858, 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.airsonic.player.service.JukeboxService", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      jukeboxService0.skip(player0, 0, 640);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Player player0 = new Player();
      PlayerTechnology playerTechnology0 = PlayerTechnology.JAVA_JUKEBOX;
      player0.setTechnology(playerTechnology0);
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      // Undeclared exception!
      try { 
        jukeboxService0.stop(player0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.airsonic.player.service.JukeboxService", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      jukeboxService0.stop(player0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      PlayerTechnology playerTechnology0 = PlayerTechnology.JUKEBOX;
      player0.setTechnology(playerTechnology0);
      // Undeclared exception!
      try { 
        jukeboxService0.stop(player0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/airsonic/player/service/SecurityService
         //
         verifyException("org.airsonic.player.service.JukeboxLegacySubsonicService", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      PlayerTechnology playerTechnology0 = PlayerTechnology.JAVA_JUKEBOX;
      player0.setTechnology(playerTechnology0);
      // Undeclared exception!
      try { 
        jukeboxService0.start(player0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.airsonic.player.service.JukeboxService", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      jukeboxService0.start(player0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      PlayerTechnology playerTechnology0 = PlayerTechnology.JUKEBOX;
      player0.setTechnology(playerTechnology0);
      // Undeclared exception!
      try { 
        jukeboxService0.start(player0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/airsonic/player/service/SecurityService
         //
         verifyException("org.airsonic.player.service.JukeboxLegacySubsonicService", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      PlayerTechnology playerTechnology0 = PlayerTechnology.JAVA_JUKEBOX;
      player0.setTechnology(playerTechnology0);
      // Undeclared exception!
      try { 
        jukeboxService0.play(player0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.airsonic.player.service.JukeboxService", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      jukeboxService0.play(player0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      PlayerTechnology playerTechnology0 = PlayerTechnology.JUKEBOX;
      player0.setTechnology(playerTechnology0);
      // Undeclared exception!
      try { 
        jukeboxService0.play(player0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/airsonic/player/service/SecurityService
         //
         verifyException("org.airsonic.player.service.JukeboxLegacySubsonicService", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      PlayerTechnology playerTechnology0 = PlayerTechnology.JAVA_JUKEBOX;
      player0.setTechnology(playerTechnology0);
      // Undeclared exception!
      try { 
        jukeboxService0.getPosition(player0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.airsonic.player.service.JukeboxService", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      jukeboxService0.getPosition(player0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      PlayerTechnology playerTechnology0 = PlayerTechnology.JUKEBOX;
      player0.setTechnology(playerTechnology0);
      jukeboxService0.getPosition(player0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      PlayerTechnology playerTechnology0 = PlayerTechnology.JUKEBOX;
      player0.setTechnology(playerTechnology0);
      // Undeclared exception!
      try { 
        jukeboxService0.updateJukebox(player0, (-1685));
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/airsonic/player/service/SecurityService
         //
         verifyException("org.airsonic.player.service.JukeboxLegacySubsonicService", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      jukeboxService0.updateJukebox(player0, (-4072));
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      PlayerTechnology playerTechnology0 = PlayerTechnology.JAVA_JUKEBOX;
      player0.setTechnology(playerTechnology0);
      // Undeclared exception!
      try { 
        jukeboxService0.getGain(player0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.airsonic.player.service.JukeboxService", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      jukeboxService0.getGain(player0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      PlayerTechnology playerTechnology0 = PlayerTechnology.JUKEBOX;
      player0.setTechnology(playerTechnology0);
      jukeboxService0.getGain(player0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      PlayerTechnology playerTechnology0 = PlayerTechnology.JAVA_JUKEBOX;
      player0.setTechnology(playerTechnology0);
      // Undeclared exception!
      try { 
        jukeboxService0.setPosition(player0, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.airsonic.player.service.JukeboxService", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      jukeboxService0.setPosition(player0, 0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      PlayerTechnology playerTechnology0 = PlayerTechnology.JUKEBOX;
      player0.setTechnology(playerTechnology0);
      // Undeclared exception!
      try { 
        jukeboxService0.setPosition(player0, 12);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.airsonic.player.service.JukeboxService", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      PlayerTechnology playerTechnology0 = PlayerTechnology.JAVA_JUKEBOX;
      player0.setTechnology(playerTechnology0);
      // Undeclared exception!
      try { 
        jukeboxService0.setGain(player0, 2639.272F);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.airsonic.player.service.JukeboxService", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      JukeboxLegacySubsonicService jukeboxLegacySubsonicService0 = new JukeboxLegacySubsonicService();
      JukeboxService jukeboxService0 = new JukeboxService(jukeboxLegacySubsonicService0, (JukeboxJavaService) null);
      Player player0 = new Player();
      jukeboxService0.setGain(player0, 2639.272F);
  }
}
