/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 15:08:17 GMT 2024
 */

package org.subsonic.restapi;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.subsonic.restapi.Child;
import org.subsonic.restapi.JukeboxPlaylist;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JukeboxPlaylist_ESTest extends JukeboxPlaylist_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JukeboxPlaylist jukeboxPlaylist0 = new JukeboxPlaylist();
      LinkedList<Child> linkedList0 = new LinkedList<Child>();
      jukeboxPlaylist0.entry = (List<Child>) linkedList0;
      Child child0 = new Child();
      linkedList0.offer(child0);
      List<Child> list0 = jukeboxPlaylist0.getEntry();
      assertTrue(list0.contains(child0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      JukeboxPlaylist jukeboxPlaylist0 = new JukeboxPlaylist();
      List<Child> list0 = jukeboxPlaylist0.getEntry();
      List<Child> list1 = jukeboxPlaylist0.getEntry();
      assertSame(list1, list0);
  }
}
