/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 15:23:58 GMT 2024
 */

package org.subsonic.restapi;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.subsonic.restapi.Share;
import org.subsonic.restapi.Shares;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Shares_ESTest extends Shares_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Shares shares0 = new Shares();
      LinkedList<Share> linkedList0 = new LinkedList<Share>();
      Share share0 = new Share();
      linkedList0.add(share0);
      shares0.share = (List<Share>) linkedList0;
      List<Share> list0 = shares0.getShare();
      assertTrue(list0.contains(share0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Shares shares0 = new Shares();
      shares0.getShare();
      List<Share> list0 = shares0.getShare();
      assertTrue(list0.isEmpty());
  }
}
