/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 06 21:17:44 GMT 2024
 */

package org.airsonic.player.command;

import org.junit.Test;
import static org.junit.Assert.*;
import org.airsonic.player.command.GeneralSettingsCommand;
import org.airsonic.player.domain.Theme;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GeneralSettingsCommand_ESTest extends GeneralSettingsCommand_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setSortAlbumsByYear(true);
      boolean boolean0 = generalSettingsCommand0.isSortAlbumsByYear();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setWelcomeTitle(",Dhu}B&}*q$S>a");
      String string0 = generalSettingsCommand0.getWelcomeTitle();
      assertEquals(",Dhu}B&}*q$S>a", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setWelcomeTitle("");
      String string0 = generalSettingsCommand0.getWelcomeTitle();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setWelcomeSubtitle("HTU[hyk5V6");
      String string0 = generalSettingsCommand0.getWelcomeSubtitle();
      assertEquals("HTU[hyk5V6", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setWelcomeSubtitle("");
      String string0 = generalSettingsCommand0.getWelcomeSubtitle();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setWelcomeMessage("F5#H?83");
      String string0 = generalSettingsCommand0.getWelcomeMessage();
      assertEquals("F5#H?83", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setWelcomeMessage("");
      String string0 = generalSettingsCommand0.getWelcomeMessage();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setVideoFileTypes("2*kPtc]&?{ji&8@)");
      String string0 = generalSettingsCommand0.getVideoFileTypes();
      assertEquals("2*kPtc]&?{ji&8@)", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setVideoFileTypes("");
      String string0 = generalSettingsCommand0.getVideoFileTypes();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      Theme[] themeArray0 = new Theme[4];
      generalSettingsCommand0.setThemes(themeArray0);
      Theme[] themeArray1 = generalSettingsCommand0.getThemes();
      assertSame(themeArray1, themeArray0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      Theme[] themeArray0 = new Theme[0];
      generalSettingsCommand0.setThemes(themeArray0);
      Theme[] themeArray1 = generalSettingsCommand0.getThemes();
      assertEquals(0, themeArray1.length);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setThemeIndex("PV,w@SUdY");
      String string0 = generalSettingsCommand0.getThemeIndex();
      assertEquals("PV,w@SUdY", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setShortcuts("w)^S\"<l>3]^:2QV.");
      String string0 = generalSettingsCommand0.getShortcuts();
      assertEquals("w)^S\"<l>3]^:2QV.", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setShortcuts("");
      String string0 = generalSettingsCommand0.getShortcuts();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setPlaylistFolder("X_.cP+vBk{(");
      String string0 = generalSettingsCommand0.getPlaylistFolder();
      assertEquals("X_.cP+vBk{(", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setPlaylistFolder("");
      String string0 = generalSettingsCommand0.getPlaylistFolder();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setMusicFileTypes("H?A.(q9y");
      String string0 = generalSettingsCommand0.getMusicFileTypes();
      assertEquals("H?A.(q9y", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setMusicFileTypes("");
      String string0 = generalSettingsCommand0.getMusicFileTypes();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setLoginMessage("org.airsonic.player.command.GeneralSettingsCommand");
      String string0 = generalSettingsCommand0.getLoginMessage();
      assertEquals("org.airsonic.player.command.GeneralSettingsCommand", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setLoginMessage("");
      String string0 = generalSettingsCommand0.getLoginMessage();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      String[] stringArray0 = new String[9];
      generalSettingsCommand0.setLocales(stringArray0);
      String[] stringArray1 = generalSettingsCommand0.getLocales();
      assertEquals(9, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      String[] stringArray0 = new String[0];
      generalSettingsCommand0.setLocales(stringArray0);
      String[] stringArray1 = generalSettingsCommand0.getLocales();
      assertEquals(0, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setLocaleIndex("o`g!&HDt([");
      String string0 = generalSettingsCommand0.getLocaleIndex();
      assertEquals("o`g!&HDt([", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setLocaleIndex("");
      String string0 = generalSettingsCommand0.getLocaleIndex();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setIndex("<f");
      String string0 = generalSettingsCommand0.getIndex();
      assertEquals("<f", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setIndex("");
      String string0 = generalSettingsCommand0.getIndex();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setIgnoredArticles("Em@5Ur,[Is|");
      String string0 = generalSettingsCommand0.getIgnoredArticles();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setIgnoredArticles("");
      String string0 = generalSettingsCommand0.getIgnoredArticles();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setCoverArtFileTypes("");
      String string0 = generalSettingsCommand0.getCoverArtFileTypes();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      String string0 = generalSettingsCommand0.getWelcomeTitle();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      String string0 = generalSettingsCommand0.getIndex();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      String string0 = generalSettingsCommand0.getThemeIndex();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      boolean boolean0 = generalSettingsCommand0.isSortAlbumsByYear();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      boolean boolean0 = generalSettingsCommand0.isGettingStartedEnabled();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setReloadNeeded(false);
      assertNull(generalSettingsCommand0.getVideoFileTypes());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      String string0 = generalSettingsCommand0.getMusicFileTypes();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      String string0 = generalSettingsCommand0.getLocaleIndex();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      String string0 = generalSettingsCommand0.getShortcuts();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      Theme[] themeArray0 = generalSettingsCommand0.getThemes();
      assertNull(themeArray0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      String string0 = generalSettingsCommand0.getPlaylistFolder();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      String string0 = generalSettingsCommand0.getVideoFileTypes();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      String string0 = generalSettingsCommand0.getWelcomeSubtitle();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      String string0 = generalSettingsCommand0.getWelcomeMessage();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setThemeIndex("");
      String string0 = generalSettingsCommand0.getThemeIndex();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setGettingStartedEnabled(true);
      boolean boolean0 = generalSettingsCommand0.isGettingStartedEnabled();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      String[] stringArray0 = generalSettingsCommand0.getLocales();
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      String string0 = generalSettingsCommand0.getLoginMessage();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      String string0 = generalSettingsCommand0.getIgnoredArticles();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      String string0 = generalSettingsCommand0.getCoverArtFileTypes();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      GeneralSettingsCommand generalSettingsCommand0 = new GeneralSettingsCommand();
      generalSettingsCommand0.setCoverArtFileTypes("GK]G+ `.2UEX/3[mu>");
      String string0 = generalSettingsCommand0.getCoverArtFileTypes();
      assertEquals("GK]G+ `.2UEX/3[mu>", string0);
  }
}
